name: Mi primer pipeline CI

on:
  push:
    branches: [ main ]

jobs:
  verificar-entorno:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Ver sistema operativo
        run: uname -a

      - name: Ver archivos del repo
        run: ls -la

      - name: Mensaje final
        run: echo "Pipeline ejecutado correctamente"

      - name: Instalar dependencias
        run: sudo apt-get install -y curl

      - name: Verificar conectividad
        run: curl -s https://api.github.com | head -5

      - name: Mostrar fecha y hora
        run: date

